### PR TITLE
implemented password page

### LINKED ISSUE #1: Password page
Since the admin dashboard has restricted access to our team only, we will need to create a password page to protect non-team-members from accessing the page.

### PR DESCRIPTION
**Pull request by teekenzie**
closes #1

### CODE REVIEW

**Review by aidenszeto — COMMENTED** [review]
Looks good so far! Can we add password verification (we can just use the password "VHomes2020" for now) that generates the token if it is valid? Once that is done we can merge.

**Comment by aidenszeto** [comment]
Also you have to add "closes" in front of the tag btw if you want to link the issue, ie "closes #1"

**Comment by teekenzie** [comment]
> Looks good so far! Can we add password verification (we can just use the password "VHomes2020" for now) that generates the token if it is valid? Once that is done we can merge.

ok my issue is that if we just hard code it in, people could just straight view our source and get the password

**Comment by aidenszeto** [comment]
Good point, how do u think we should implement the password? Maybe create a route that checks in the backend?

**Comment by teekenzie** [comment]
yeah, that's what i have been thinking. We should also put it into the dotevn file in the backend

**Comment by teekenzie** [comment]
used axios to call the backend to verify the password

**Review by aidenszeto — APPROVED** [review]

**Comment by aidenszeto** [comment]
Looks good, feel free to merge when youre ready

**Pull request merged**
